// <auto-generated />
using System;
using FloreriaBautista.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FloreriaBautista.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("calle");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("colonia");

                    b.Property<string>("Cp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cp");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("Referencias")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referencias");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_addresses_customer_id");

                    b.ToTable("addresses", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalles")
                        .HasColumnType("text")
                        .HasColumnName("detalles");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("ix_audit_logs_fecha_hora");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_audit_logs_usuario_id");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_audit_logs_entidad_entidad_id");

                    b.ToTable("audit_logs", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean")
                        .HasColumnName("usado");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_tokens_user_id");

                    b.ToTable("auth_tokens", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.BackupJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("DriveFileId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("drive_file_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("BACKUP")
                        .HasColumnName("formato");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text")
                        .HasColumnName("mensaje_error");

                    b.Property<string>("NombreTabla")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_tabla");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_backup_jobs");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_backup_jobs_usuario_id");

                    b.ToTable("backup_jobs", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Catalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVA")
                        .HasColumnName("estado");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_catalogos");

                    b.ToTable("catalogos", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVA")
                        .HasColumnName("estado");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("CpFiscal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cp_fiscal");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenFiscal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("regimen_fiscal");

                    b.Property<string>("Rfc")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("rfc");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cliente");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Telefono")
                        .HasDatabaseName("ix_customers_telefono");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("customers", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.CustomizationOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("clave");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Opciones")
                        .HasColumnType("text")
                        .HasColumnName("opciones");

                    b.Property<decimal>("PrecioAdicional")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_adicional");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_customization_options");

                    b.ToTable("customization_options", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EstadoEntrega")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado_entrega");

                    b.Property<string>("EvidenciaFotografica")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("evidencia_fotografica");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_programada");

                    b.Property<DateTime?>("FechaReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_real");

                    b.Property<string>("FirmaReceptor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("firma_receptor");

                    b.Property<TimeOnly?>("HoraProgramada")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_programada");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("RepartidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("repartidor_id");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_deliveries_order_id");

                    b.HasIndex("RepartidorId")
                        .HasDatabaseName("ix_deliveries_repartidor_id");

                    b.ToTable("deliveries", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completado_en");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estado");

                    b.Property<string>("Resumen")
                        .HasColumnType("text")
                        .HasColumnName("resumen");

                    b.Property<string>("TipoImportacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_importacion");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_import_jobs_usuario_id");

                    b.ToTable("import_jobs", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.InventoryDailySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CantidadRecibida")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_recibida");

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_vendida");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<int>("StockFinal")
                        .HasColumnType("integer")
                        .HasColumnName("stock_final");

                    b.HasKey("Id")
                        .HasName("pk_inventory_daily_snapshot");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_daily_snapshot_inventory_item_id");

                    b.ToTable("inventory_daily_snapshot", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("EsFlorPrimaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_flor_primaria");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio_costo");

                    b.Property<int>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_actual");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_minimo");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sucursal");

                    b.Property<bool>("SumaAlCosto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("suma_al_costo");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.ToTable("inventory_items", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_movements_inventory_item_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_inventory_movements_usuario_id");

                    b.ToTable("inventory_movements", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<decimal?>("CostoEnvio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_envio");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DireccionEntregaCalle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("direccion_entrega_calle");

                    b.Property<string>("DireccionEntregaColonia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("direccion_entrega_colonia");

                    b.Property<string>("DireccionEntregaCp")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direccion_entrega_cp");

                    b.Property<string>("DireccionEntregaEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("direccion_entrega_estado");

                    b.Property<string>("DireccionEntregaMunicipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("direccion_entrega_municipio");

                    b.Property<string>("DireccionEntregaReferencias")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("direccion_entrega_referencias");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDIENTE_VALIDACION")
                        .HasColumnName("estado_pedido");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<TimeOnly?>("HoraEntrega")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_entrega");

                    b.Property<Guid?>("IdLocalOffline")
                        .HasColumnType("uuid")
                        .HasColumnName("id_local_offline");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<decimal>("SaldoPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo_pendiente");

                    b.Property<DateTime?>("SincronizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sincronizado_en");

                    b.Property<string>("TipoPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_pedido");

                    b.Property<decimal>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("IdLocalOffline")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_id_local_offline")
                        .HasFilter("id_local_offline IS NOT NULL");

                    b.ToTable("orders", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.ToTable("order_items", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.OrderItemCustomization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomizationOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("customization_option_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<string>("Valor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_order_item_customizations");

                    b.HasIndex("CustomizationOptionId")
                        .HasDatabaseName("ix_order_item_customizations_customization_option_id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_order_item_customizations_order_item_id");

                    b.ToTable("order_item_customizations", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("REGISTRADO")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_pago");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payments_order_id");

                    b.ToTable("payments", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsPersonalizable")
                        .HasColumnType("boolean")
                        .HasColumnName("es_personalizable");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estado");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_base");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("Visibilidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("AMBOS")
                        .HasColumnName("visibilidad");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductCatalogo", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CatalogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogo_id");

                    b.HasKey("ProductId", "CatalogoId")
                        .HasName("pk_product_catalogos");

                    b.HasIndex("CatalogoId")
                        .HasDatabaseName("ix_product_catalogos_catalogo_id");

                    b.ToTable("product_catalogos", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("ProductId", "CategoryId")
                        .HasName("pk_product_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_categories_category_id");

                    b.ToTable("product_categories", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductCustomizationOption", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("CustomizationOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("customization_option_id");

                    b.HasKey("ProductId", "CustomizationOptionId")
                        .HasName("pk_product_customization_options");

                    b.HasIndex("CustomizationOptionId")
                        .HasDatabaseName("ix_product_customization_options_customization_option_id");

                    b.ToTable("product_customization_options", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CantidadRequerida")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_requerida");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_recipes");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_product_recipes_inventory_item_id");

                    b.HasIndex("ProductId", "InventoryItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_recipes_product_id_inventory_item_id");

                    b.ToTable("product_recipes", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.SchedulerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("BackupAutomaticoActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("backup_automatico_activo");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<int>("DiaSemanaMantenimiento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana_mantenimiento");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SEMANAL")
                        .HasColumnName("frecuencia");

                    b.Property<string>("FrecuenciaMantenimiento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SEMANAL")
                        .HasColumnName("frecuencia_mantenimiento");

                    b.Property<int>("Hora")
                        .HasColumnType("integer")
                        .HasColumnName("hora");

                    b.Property<int>("HoraMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("hora_mantenimiento");

                    b.Property<bool>("MantenimientoActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("mantenimiento_activo");

                    b.HasKey("Id")
                        .HasName("pk_scheduler_settings");

                    b.ToTable("scheduler_settings", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("CorreoVerificado")
                        .HasColumnType("boolean")
                        .HasColumnName("correo_verificado");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("EsCliente")
                        .HasColumnType("boolean")
                        .HasColumnName("es_cliente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_users_correo");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "public");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Address", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_customer_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_audit_logs_user_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.AuthToken", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.User", "User")
                        .WithMany("AuthTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_tokens_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.BackupJob", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_backup_jobs_user_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Customer", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("FloreriaBautista.Models.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customers_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Delivery", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("FloreriaBautista.Models.Entities.Delivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deliveries_order_order_id");

                    b.HasOne("FloreriaBautista.Models.Entities.User", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .HasConstraintName("fk_deliveries_user_repartidor_id");

                    b.Navigation("Order");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ImportJob", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_import_jobs_user_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.InventoryDailySnapshot", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_daily_snapshot_inventory_item_inventory_item_id");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.InventoryMovement", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.InventoryItem", "InventoryItem")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_inventory_items_inventory_item_id");

                    b.HasOne("FloreriaBautista.Models.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_user_usuario_id");

                    b.Navigation("InventoryItem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Order", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("FloreriaBautista.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_product_product_id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.OrderItemCustomization", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.CustomizationOption", "CustomizationOption")
                        .WithMany("OrderItemCustomizations")
                        .HasForeignKey("CustomizationOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_customizations_customization_options_customizati");

                    b.HasOne("FloreriaBautista.Models.Entities.OrderItem", "OrderItem")
                        .WithMany("OrderItemCustomizations")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_item_customizations_order_items_order_item_id");

                    b.Navigation("CustomizationOption");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Payment", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductCatalogo", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Catalogo", "Catalogo")
                        .WithMany("ProductCatalogos")
                        .HasForeignKey("CatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_catalogos_catalogos_catalogo_id");

                    b.HasOne("FloreriaBautista.Models.Entities.Product", "Product")
                        .WithMany("ProductCatalogos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_catalogos_products_product_id");

                    b.Navigation("Catalogo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductCategory", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_categories_category_id");

                    b.HasOne("FloreriaBautista.Models.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_categories_products_product_id");

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductCustomizationOption", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.CustomizationOption", "CustomizationOption")
                        .WithMany("ProductCustomizationOptions")
                        .HasForeignKey("CustomizationOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_customization_options_customization_options_customi");

                    b.HasOne("FloreriaBautista.Models.Entities.Product", "Product")
                        .WithMany("ProductCustomizationOptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_customization_options_products_product_id");

                    b.Navigation("CustomizationOption");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.ProductRecipe", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.InventoryItem", "InventoryItem")
                        .WithMany("ProductRecipes")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_recipes_inventory_items_inventory_item_id");

                    b.HasOne("FloreriaBautista.Models.Entities.Product", "Product")
                        .WithMany("ProductRecipes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_recipes_products_product_id");

                    b.Navigation("InventoryItem");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.UserRole", b =>
                {
                    b.HasOne("FloreriaBautista.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("FloreriaBautista.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Catalogo", b =>
                {
                    b.Navigation("ProductCatalogos");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.CustomizationOption", b =>
                {
                    b.Navigation("OrderItemCustomizations");

                    b.Navigation("ProductCustomizationOptions");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.InventoryItem", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("ProductRecipes");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Order", b =>
                {
                    b.Navigation("Delivery");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.OrderItem", b =>
                {
                    b.Navigation("OrderItemCustomizations");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductCatalogos");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductCustomizationOptions");

                    b.Navigation("ProductRecipes");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FloreriaBautista.Models.Entities.User", b =>
                {
                    b.Navigation("AuthTokens");

                    b.Navigation("Customer");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
